---
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: s1
        server-id: central
        server-username: CENTRAL_USERNAME
        server-password: CENTRAL_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
        cache: maven
    - name: Build with Maven
      run: mvn -B -fn
    - name: Publish test results
      uses: scacap/action-surefire-report@v1
    - name: Publish to codecov
      uses: codecov/codecov-action@v3
      continue-on-error: true
      if: ${{ github.event_name == 'push' }}
    - name: Deploy with Maven
      run: mvn -B -Pdeploy  -DskipTests=true deploy
      if: ${{ github.event_name == 'push' }}
      env:
        CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

